import type { RankDefinition } from '../types'

export const RANKS: RankDefinition[] = [
  {
    id: 'soldado',
    name: 'Soldado',
    minDays: 0,
    maxDays: 2,
    icon: '🪖',
    description: 'Recruta em treinamento básico.',
    rarity: 'common',
    unlocks: ['Uniforme básico'],
    avatarConfig: { armor: 'basic' },
  },
  {
    id: 'cabo',
    name: 'Cabo',
    minDays: 3,
    maxDays: 4,
    icon: '⭐',
    description: 'Primeira distinção no campo.',
    rarity: 'common',
    unlocks: ['Uniforme melhorado'],
    avatarConfig: { armor: 'basic' },
  },
  {
    id: '3-sargento',
    name: '3º Sargento',
    minDays: 5,
    maxDays: 6,
    icon: '🎖️',
    description: 'Insígnias e ombreiras leves.',
    rarity: 'uncommon',
    unlocks: ['Insígnias', 'Ombreiras básicas'],
    avatarConfig: { armor: 'sergeant', shoulders: 'basic' },
  },
  {
    id: '2-sargento',
    name: '2º Sargento',
    minDays: 7,
    maxDays: 8,
    icon: '🎖️',
    description: 'Veterano em ascensão.',
    rarity: 'uncommon',
    unlocks: ['Armadura leve'],
    avatarConfig: { armor: 'sergeant', shoulders: 'basic' },
  },
  {
    id: '1-sargento',
    name: '1º Sargento',
    minDays: 9,
    maxDays: 10,
    icon: '🎖️',
    description: 'Elite dos sargentos.',
    rarity: 'uncommon',
    unlocks: ['Armadura reforçada'],
    avatarConfig: { armor: 'sergeant', shoulders: 'basic', weapon: 'sword-basic' },
  },
  {
    id: 'subtenente',
    name: 'Subtenente',
    minDays: 11,
    maxDays: 12,
    icon: '⚔️',
    description: 'Armadura intermediária desbloqueada.',
    rarity: 'rare',
    unlocks: ['Armadura intermediária'],
    avatarConfig: { armor: 'officer', shoulders: 'basic' },
  },
  {
    id: 'aspirante',
    name: 'Aspirante a Oficial',
    minDays: 13,
    maxDays: 14,
    icon: '🛡️',
    description: 'Pequena capa de oficial.',
    rarity: 'rare',
    unlocks: ['Capa básica'],
    avatarConfig: { armor: 'officer', shoulders: 'basic', cape: 'basic' },
  },
  {
    id: '2-tenente',
    name: '2º Tenente',
    minDays: 15,
    maxDays: 16,
    icon: '⚔️',
    description: 'Uniforme de oficial.',
    rarity: 'rare',
    unlocks: ['Espada de oficial'],
    avatarConfig: { armor: 'officer', cape: 'basic', weapon: 'sword-officer' },
  },
  {
    id: '1-tenente',
    name: '1º Tenente',
    minDays: 17,
    maxDays: 18,
    icon: '⚔️',
    description: 'Elementos nobres desbloqueados.',
    rarity: 'rare',
    unlocks: ['Elementos nobres'],
    avatarConfig: { armor: 'officer', cape: 'officer', weapon: 'sword-officer' },
  },
  {
    id: 'capitao',
    name: 'Capitão',
    minDays: 19,
    maxDays: 20,
    icon: '🎖️',
    description: 'Armadura completa e capa.',
    rarity: 'epic',
    unlocks: ['Armadura completa', 'Capa de capitão'],
    avatarConfig: { armor: 'captain', cape: 'officer', weapon: 'sword-officer' },
  },
  {
    id: 'major',
    name: 'Major',
    minDays: 21,
    maxDays: 22,
    icon: '🏅',
    description: 'Medalhas e equipamentos superiores.',
    rarity: 'epic',
    unlocks: ['Medalhas'],
    avatarConfig: { armor: 'captain', cape: 'officer', weapon: 'sword-officer', effects: ['stars'] },
  },
  {
    id: 'coronel',
    name: 'Coronel',
    minDays: 23,
    maxDays: 24,
    icon: '🦅',
    description: 'Visual de elite.',
    rarity: 'epic',
    unlocks: ['Visual de elite'],
    avatarConfig: { armor: 'captain', shoulders: 'elite', cape: 'officer', weapon: 'sword-officer', effects: ['stars'] },
  },
  {
    id: 'general',
    name: 'General',
    minDays: 25,
    maxDays: 26,
    icon: '⭐⭐⭐',
    description: 'Armadura dourada e três estrelas.',
    rarity: 'legendary',
    unlocks: ['Armadura do General', 'Capa real', 'Arma especial'],
    avatarConfig: {
      armor: 'general',
      shoulders: 'elite',
      cape: 'royal',
      weapon: 'sword-legendary',
      head: 'general-helmet',
      effects: ['stars'],
    },
  },
  {
    id: 'rei',
    name: 'Rei',
    minDays: 27,
    maxDays: 28,
    icon: '👑',
    description: 'Coroa, manto e armadura real.',
    rarity: 'legendary',
    unlocks: ['Coroa', 'Manto real', 'Armadura real'],
    avatarConfig: {
      armor: 'general',
      shoulders: 'elite',
      cape: 'royal',
      weapon: 'sword-legendary',
      head: 'crown',
      effects: ['stars'],
    },
  },
  {
    id: 'monge',
    name: 'Monge ∞',
    minDays: 29,
    maxDays: 30,
    icon: '∞',
    description: 'Transformação lendária. Você transcendeu.',
    rarity: 'mythic',
    unlocks: ['Túnica especial', 'Aura lendária'],
    avatarConfig: {
      armor: 'general',
      cape: 'royal',
      weapon: 'sword-legendary',
      effects: ['monk-aura', 'aura'],
    },
  },
]

export const RANK_BY_ID = Object.fromEntries(RANKS.map((r) => [r.id, r])) as Record<string, RankDefinition>
